messages:
  command-usage-message: "Please provide the correct arguments for this command:
  \n/bomberman join - Join a bomberman game.
  \n/bomberman leave - Leaves a bomberman game.
  \n/bomberman stats - Sees your current bomberman stats."
  player-join-queue-message: "[Bomberman] You have joined the queue to play a bomberman game when it is available."
  eliminated-message: "[Bomberman] %player% was eliminated by %bomber%"
  no-permission-message: "[Bomberman] You don't have permission to use that command."
  no-game-available: "[Bomberman] There are no available games at the moment."
  queue-message: "[Bomberman] You were put on a queue to play."
  not-playing-message: "[Bomberman] You are not in a bomberman game to use this command."
  not-done-yet: "[Bomberman] This feature is not available yet."
  bomberman-off: "[Bomberman] You have closed the bomberman games, to cancel all the current games running use /bomberman cancel."
  bomberman-on: "[Bomberman] You have set the bomberman games to open."
  join-game-message: "[Bomberman] Place bombs to destroy tiles and eliminate your enemies. You can find some perks by destroying
   tiles."
  leave-game-message: "[Bomberman] %player% left the game."
  eliminated-itself: "[Bomberman] %player% eliminated itself."
  game-cancelled-message: "[Bomberman] This game was cancelled."
  warmup-message: "[Bomberman] The game is going to start soon, be prepared!"
  bossbar-message: "%delay% to start the game"
  life-lost-message: "[Bomberman] You have lost one life."
  command-blocked-message: "[Bomberman] This command is blocked in this game. Try using /bomberman leave to leave the game."
  winner-message: "[Bomberman] %winner% is the winner!"
  title-sidebar: "BOMBERMAN"
  bombs-sidebar: "Bombs -> "
  power-sidebar: "Power -> "
  landmines-sidebar: "LandMines -> "
  kills-sidebar: "Kills -> "
  extra-bomb-message: "[Bomberman] You got an extra bomb."
  extra-landmine-message: "[Bomberman] You got a landmine."
  extra-power-message: "[Bomberman] Now your bombs have more power."
  shovel-message: "[Bomberman] Now you can move bombs using your shovel."
  boots-message: "[Bomberman] Now you can kick bombs away with your boots."
  extra-life-message: "[Bomberman] You got an extra life."
  speed-message: "[Bomberman] You are faster now."
  blindness-message: "[Bomberman] Somebody turned the lights off."
  clock-message: "[Bomberman] Now you control the time your bombs explode using the clock."

allowed-commands: ["bomberman","tell","msg"]